version: "3.7"

services:
  # MariaDB
  db:
    image: mariadb:10.8.2 # change to 10.10 or 10.11 to test those versions
    restart: "unless-stopped"
    command:
      - mysqld
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
      - --general-log=1
      - --general-log-file=openmrs_db.log
    healthcheck:
      test: "mysql --user=${OMRS_DB_USER:-openmrs} --password=${OMRS_DB_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openmrs}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3309:3306"

volumes:
  db-data: ~

